### ISSUE TITLE
Typo, link, force refresh

### ISSUE THREAD

**Issue by hunan-rostomyan** [ericdwang/pybart#1]
1. (Typo) There may be a typo in the README, "curses based..." should probably be capitalized to be consistent with the other list items.
2. (Suggestion) Might want to add a link to bart.gov where you first mention "Bay Area Rapid Transit"
3. (Feature request) It'd be nice to be able to _force-refresh_ while on the station list (maybe by pressing 'r'). Right now it's only possible to quite by pressing 'q'.

Thanks for the useful tool.

**Comment by ericdwang** [comment]
1. I actually debated doing that, but I saw "curses" usually spelled as lowercase so I left it that way. It does look inconsistent though and kind of bothers me too.
2. Yeah, that's another thing I debated doing, haha. I think it'd be good to add, I just forgot about it.
3. As an unintended consequence of how I made this thing, you can actually force-refresh by pressing any key besides 'q', haha. I guess it's a feature, not a bug!

**Comment by hunan-rostomyan** [comment]
(1) I did suspect that's the reason you left it uncapitalized. In that case, consider adding a link to (https://docs.python.org/3/library/curses.html), as not everyone might be familiar with the module.

(3) Hahaha. Cool, cool.

**Comment by ericdwang** [comment]
Decided to add a link to the curses Wikipedia article instead since it's actually not a Python specific library. Thanks for the suggestions!
